name: CI Pull Request
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  validate:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v0.8.3
        with:
          workload_identity_provider: projects/401363556022/locations/global/workloadIdentityPools/automation/providers/github
          service_account: automation@automation-220928.iam.gserviceaccount.com
      - run: terraform -chdir=src init -upgrade
      - run: terraform -chdir=src validate
